# Generated by cpp11: do not edit by hand

cpp_mm_version <- function() {
  .Call(`_headings_cpp_mm_version`)
}

cpp_mm_read_coef <- function(filename_utf8) {
  .Call(`_headings_cpp_mm_read_coef`, filename_utf8)
}

cpp_mm_ellipsoidal_height <- function(coords, geoid_ints) {
  .Call(`_headings_cpp_mm_ellipsoidal_height`, coords, geoid_ints)
}

cpp_mm_extract <- function(model_sexp, coords) {
  .Call(`_headings_cpp_mm_extract`, model_sexp, coords)
}
