
#' NCEI World Magnetic Model 2020
#'
#' @param lon,lat Coordinates in WGS84 datum
#' @param year A decimal year (e.g., 2020.2120). The World Magnetic Model
#'   is valid between 2020 and 2025
#' @param date An R date object or value that can be coerced to one.
#' @param height Height above the WGS84 ellipsoid in kilometers.
#' @param coef Model coefficients as generated by [wmm_read_coefficients()], or
#'   `NULL` for the default WMM 2020 values.
#' @param file Path to a ".COF" file containing coefficients in the form
#'   required by the model.
#'
#' @return A data frame with columns - `decl`: Magnetic variation in degrees -
#'   `incl`: Inclination of the magnetic field in degrees - `decl_err`,
#'   `incl_err`: Error associated with declination and inclination,
#'   respectively.
#' @export
#'
#' @references
#' NCEI World Magnetic Model <https://www.ngdc.noaa.gov/geomag/WMM/DoDWMM.shtml>.
#'
#' NCEI Geomagnetic Modeling Team and British Geological Survey.
#' 2019. World Magnetic Model 2020. NOAA National Centers for Environmental
#' Information. \doi{10.25921/11v3-da71}, 2020, accessed 2021-02-23.
#'
#' Chulliat, A., W. Brown, P. Alken, C. Beggan, M. Nair, G. Cox, A. Woods, S.
#' Macmillan, B. Meyer and M. Paniccia, The US/UK World Magnetic Model for
#' 2020-2025: Technical Report, National Centers for Environmental Information,
#' NOAA, \doi{10.25923/ytk1-yx35}, 2020.
#'
#' @examples
#' wmm_version()
#' wmm_extract(-64, 45, wmm_decimal_year("2021-01-01"))
#'
wmm_extract <- function(lon, lat, year = wmm_decimal_year(Sys.Date()),
                        height = 0, coef = NULL) {
  if (is.null(coef)) {
    coef <- wmm_read_coefficients(system.file("extdata/WMM.COF", package = "headings"))
  }

  lon <- vctrs::vec_cast(lon, double())
  lat <- vctrs::vec_cast(lat, double())
  height <- vctrs::vec_cast(height, double())
  year <- vctrs::vec_cast(year, double())

  coords <- vctrs::vec_recycle_common(
    lambda = lon,
    phi = lat,
    height = height,
    year = year
  )

  cpp_wmm_extract(coef, coords)
}

#' @rdname wmm_extract
#' @export
wmm_read_coefficients <- function(file) {
  cpp_wmm_read_coef(path.expand(file));
}


#' @rdname wmm_extract
#' @export
wmm_decimal_year <- function(date) {
  date <- as.Date(date)
  date_lt <- as.POSIXlt(date)
  (date_lt$year + 1900) + date_lt$yday / 365
}

#' @rdname wmm_extract
#' @export
wmm_version <- function() {
  cpp_wmm_version()
}
